import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Margin_width_wrapper from "@/components/wrappers/margin_width_wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import Page_wrapper from "@/components/wrappers/page_wrapper";
import Navbar from "@/components/NavBar";
import SideBar from "@/components/SideBar";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import Footer from "@/components/Footer";
import { Toaster, toast } from 'sonner'

const iBM_Plex_Sans = IBM_Plex_Sans({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={iBM_Plex_Sans.className} suppressHydrationWarning={true}>
        <Margin_width_wrapper>
          <TooltipProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster richColors  />
            <Navbar />
            <SideBar />
            <Page_wrapper>{children}</Page_wrapper>
            <Footer />
          </ThemeProvider>
          </TooltipProvider>
        </Margin_width_wrapper>
      </body>
    </html>
  );
}
